/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package review1;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author KirkThunder
 */
public class Index1 extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Index1() {
        initComponents();

    }
    public int countIDRestaurant;

    public Index1(int x) {
        countIDRestaurant = x;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        nextbtn = new javax.swing.JButton();
        backbtn1 = new javax.swing.JButton();
        name1 = new javax.swing.JButton();
        name3 = new javax.swing.JButton();
        name4 = new javax.swing.JButton();
        name2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        jPanel2.setBackground(new java.awt.Color(235, 235, 248));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Restaurant Review");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/review1/45167938_2171638419830989_450212688308469760_n.jpg"))); // NOI18N
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.setInheritsPopupMenu(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 480, 360, 270));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/review1/ตำอีหลีอีหลอ (2).jpg"))); // NOI18N
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 370, 270));

        jButton4.setBackground(new java.awt.Color(235, 235, 248));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/review1/โจ๊กหมูทอง.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 140, 360, 224));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/review1/ก๋วยเตี๋ยวต้มยำไช่สะดุ้ง.jpg"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 370, 240));

        nextbtn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        nextbtn.setText("Next");
        nextbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbtnActionPerformed(evt);
            }
        });
        jPanel2.add(nextbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 790, -1, 40));

        backbtn1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        backbtn1.setText("Back");
        backbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(backbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 790, -1, 40));

        name1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                name1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });
        jPanel2.add(name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 210, 40));

        name3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                name3AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        name3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name3ActionPerformed(evt);
            }
        });
        jPanel2.add(name3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 260, 40));

        name4.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                name4AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        name4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name4ActionPerformed(evt);
            }
        });
        jPanel2.add(name4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 420, 240, 40));

        name2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                name2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        name2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name2ActionPerformed(evt);
            }
        });
        jPanel2.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 240, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1106, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public int IDrestaurant = 0;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        Review change = new Review();
        change.setVisible(true);
        IDrestaurant = 3;


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        setVisible(false);
        Review change = new Review();
        change.setVisible(true);
        IDrestaurant = 1;


    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        setVisible(false);
        Review change = new Review();
        change.setVisible(true);
        IDrestaurant = 2;


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        setVisible(false);
        Review change = new Review();
        change.setVisible(true);
        IDrestaurant = 4;


    }//GEN-LAST:event_jButton2ActionPerformed

    private void nextbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbtnActionPerformed
        setVisible(false);
        Index1 change = new Index1(countIDRestaurant);
        change.setVisible(true);
        countIDRestaurant = countIDRestaurant + 4;
    }//GEN-LAST:event_nextbtnActionPerformed

    private void name1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_name1AncestorAdded
        try {

            name1.setText("" + getname(countIDRestaurant + 1));
        } catch (SQLException ex) {
            Logger.getLogger(Index1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_name1AncestorAdded

    private void name3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_name3AncestorAdded
        try {
            name3.setText("" + getname(countIDRestaurant + 3));
        } catch (SQLException ex) {
            Logger.getLogger(Index1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_name3AncestorAdded

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed

    }//GEN-LAST:event_name1ActionPerformed

    private void name4AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_name4AncestorAdded
        try {
            name4.setText("" + getname(countIDRestaurant + 4));
        } catch (SQLException ex) {
            Logger.getLogger(Index1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_name4AncestorAdded

    private void name2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_name2AncestorAdded
        try {

            name2.setText("" + getname(countIDRestaurant + 2));
        } catch (SQLException ex) {
            Logger.getLogger(Index1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_name2AncestorAdded

    private void name2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name2ActionPerformed
        {
         }    }//GEN-LAST:event_name2ActionPerformed

    private void name3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name3ActionPerformed

    }//GEN-LAST:event_name3ActionPerformed

    private void name4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name4ActionPerformed

    }//GEN-LAST:event_name4ActionPerformed

    private void backbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtn1ActionPerformed
       /*  setVisible(false);
        
              countIDRestaurant = countIDRestaurant - 4;
        Index1 change = new Index1(countIDRestaurant);
     change.setVisible(true);*/
    }//GEN-LAST:event_backbtn1ActionPerformed

    public static String getname(int x) throws SQLException {
        String name01 = "";
        int numpage = x;
        try {
            db db = new db();

            PreparedStatement pst;
            Connection connection;
            connection = DriverManager.getConnection(db.url, db.username, db.password);
            Statement stmt = connection.createStatement();
            String countfromdatabase = "Select NameRestaurant From Restaurant WHERE idRestaurant= " + numpage;
            ResultSet rs = stmt.executeQuery(countfromdatabase);
            while (rs.next()) {
                name01 = rs.getString("NameRestaurant");

            }
        } catch (SQLException ex) {

        }

        return name01;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index1().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton name1;
    private javax.swing.JButton name2;
    private javax.swing.JButton name3;
    private javax.swing.JButton name4;
    private javax.swing.JButton nextbtn;
    // End of variables declaration//GEN-END:variables
}
